### ISSUE TITLE
Change font 

### ISSUE THREAD

**Issue by KangerCoder** [yashoswalyo/TorToolkitX#3]
How can we change fonts to mono in your repo. When it uploads to telegram..

**Comment by yashoswalyo** [comment]
Change this lines to:- 
```python
caption_str += f"`{file_name}`"
```


https://github.com/yashoswalyo/TorToolkitX/blob/5e67d9c2721a96154abea8c92b40f177aefa3f6f/tortoolkit/functions/tele_upload.py#L297

https://github.com/yashoswalyo/TorToolkitX/blob/5e67d9c2721a96154abea8c92b40f177aefa3f6f/tortoolkit/functions/tele_upload.py#L516
